# Generated by Django 6.0.6 on 2026-06-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemprice',
            options={'verbose_name': 'Item Price', 'verbose_name_plural': 'Item Prices'},
        ),
        migrations.AlterModelOptions(
            name='itemunit',
            options={'verbose_name': 'Item Unit', 'verbose_name_plural': 'Item Units'},
        ),
    ]
