# Generated by Django 6.0.6 on 2026-06-13 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ex_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('attention', models.CharField(blank=True, max_length=255)),
                ('pay_terms', models.CharField(blank=True, max_length=255)),
                ('delivery_place', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('valid_until', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('quotation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.quotationtype')),
                ('sales_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesexecutive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ex_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('attention', models.CharField(blank=True, max_length=255)),
                ('pay_terms', models.CharField(blank=True, max_length=255)),
                ('delivery_place', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('so_no', models.CharField(max_length=50, unique=True)),
                ('customer_po', models.CharField(blank=True, max_length=100)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.ordertype')),
                ('sales_executive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesexecutive')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesquotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disc_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('disc_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_after_vat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unittype')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesquotation')),
            ],
        ),
    ]
