# Generated by Django 6.0.6 on 2026-06-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='cust_ref_num',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='cust_ref_num',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
