# Generated by Django 6.0.6 on 2026-06-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder_cust_ref_num_salesquotation_cust_ref_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
