# Generated by Django 6.0.6 on 2026-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesquotation_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesquotation',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
